# Generated by Django 4.1.4 on 2022-12-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='cash',
            field=models.DecimalField(decimal_places=1, max_digits=9, verbose_name='Сумма'),
        ),
    ]
